### ISSUE TITLE
delete automotive-assembly-line files

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_environments#93]
we should delete all files related to automotive-assemly-line (which came in via #91) because this environment is not part of the default environments supported by this package.

Discussion about default environments see #92.

**Comment by floweisshardt** [comment]
done in #94

**Comment by floweisshardt** [comment]
Needs to be deleted fromhttps://github.com/ipa320/cob_simulation/tree/indigo_dev/cob_gazebo_worlds too.

**Comment by fmessmer** [comment]
This has been discussed in favor of keeping the environment as a more industrial-like demo scenario for navigation
